version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    groups:
      npm-development:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5

  - package-ecosystem: "gomod"
    directory: "/services/local-bridge"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
